---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/video/lostfilm:/lostfilm
      - /mnt/video/anilibria:/anilibria
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  false-mirror:
    platform: linux/x86_64
    image: icyberdeveloper/false-mirror:latest
    container_name: false-mirror
    volumes:
      - /storage:/storage
    restart: unless-stopped
