---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /mnt/video/lostfilm:/lostfilm_1
      - /mnt/video/anilibria:/anilibria_1
      - /mnt/video2/lostfilm:/lostfilm_2
      - /mnt/video2/anilibria:/anilibria_2
      - /storage/data:/config
    network_mode: "host"
    restart: unless-stopped

  false-mirror:
    platform: linux/x86_64
    image: icyberdeveloper/false-mirror:latest
    container_name: false-mirror
    volumes:
      - /storage:/storage
    network_mode: "host"
    restart: unless-stopped
