---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6882
    volumes:
      - /storage/qbittorrent:/config
      - /mnt/library:/downloads
      - /mnt/tmp:/incomplete
    network_mode: "host"
    restart: unless-stopped

  false-mirror:
    platform: linux/x86_64
    image: icyberdeveloper/false-mirror:latest
    container_name: false-mirror
    volumes:
      - /storage:/storage
    network_mode: "host"
    restart: unless-stopped
    depends_on:
      qbittorrent:
        condition: service_started
