global:
  proxy:
    enabled: false
    host: '127.0.0.1'
    port: 1080

qbittorrent:
  host: '127.0.0.1'
  port: 8080
  username: 'admin'
  password: 'adminadmin'
  download_dir: '/downloads/TV Shows'
  anime_dir: '/downloads/Anime'
  movies_dir: '/downloads/Movies'
  incomplete_dir: '/incomplete'

anilibria:
  torrent_mirror: 'https://www.anilibria.tv'
  api_mirror: 'https://api.anilibria.tv'
  db_path: '/storage/anilibria.json'

lostfilm:
  lf_session: ''  # set via LF_SESSION env var
  torrent_mirror: 'https://www.lostfilm.tv'
  db_path: '/storage/lostfilm.json'

renamer:
  root_dir: '/library'
  anilibria:
    regex: '(?P<name>.+)_\[(?P<episode>\d{2})(?:_\w+)?\](?:_\[[^\]]+\])*\.mkv'

nocronbot:
  token: ''  # set via TG_BOT_TOKEN env var
