global:
  interval: 60 # minutes
  proxy:
    enabled: true
    host: '127.0.0.1'
    port: 1080


qbittorrent:
  host: '127.0.0.1'
  port: 8080
  username: 'admin'
  password: 'adminadmin'
  download_dir: '/downloads/TV Shows'
  db_path: '/storage/qbittorrent.json'


anilibria:
  torrent_mirrors:
    - 'https://www.anilibria.tv'
  api_mirrors:
    - 'https://api.anilibria.tv'
  db_path: '/storage/anilibria.json'


lostfilm:
  lf_session: "5dd9ff9da1fdac450fd1bc10e77186d3.2214896"
  torrent_mirrors:
    - 'https://www.lostfilm.tv'
  db_path: '/storage/lostfilm.json'


renamer:
  root_dir: '/mnt/library'
  anilibria:
    regex: '(?P<name>\w+)_\[(?P<episode>\d{2})]_\[\w+]_\[\w+]\.mkv'


nocronbot:
  token: '6934685680:AAF1uNpBNVya6ljNFrxahUsli4ZezRstZYo'

thetvdb:
  api_key: '62ec625e-c313-4276-aebb-a847002a07fc'