services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6882
    volumes:
      - /storage/qbittorrent:/config
      - /mnt/library:/downloads
      - /mnt/tmp:/incomplete
    network_mode: host
    restart: unless-stopped

  false-mirror:
    image: icyberdeveloper/false-mirror:latest
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: false-mirror
    environment:
      - LF_SESSION=9277a695061f92112a9671814ecf230b.2214896
      - TG_BOT_TOKEN=6934685680:AAF1uNpBNVya6ljNFrxahUsli4ZezRstZYo
      - HEALTHCHECK_TG_CHAT_ID=197650166
    volumes:
      - /storage:/storage
      - /mnt/library:/library
      - /mnt/tmp:/incomplete
    network_mode: host
    restart: unless-stopped
    depends_on:
      qbittorrent:
        condition: service_started

  bot:
    image: icyberdeveloper/nocron:latest
    build:
      context: ..
      dockerfile: deploy/Dockerfile.bot
    container_name: nocron
    environment:
      - TG_BOT_TOKEN=6934685680:AAF1uNpBNVya6ljNFrxahUsli4ZezRstZYo
      - LF_SESSION=9277a695061f92112a9671814ecf230b.2214896
      - HEALTHCHECK_TG_CHAT_ID=197650166
    volumes:
      - /storage:/storage
      - /mnt/library:/library
      - /mnt/tmp:/incomplete
    network_mode: host
    restart: unless-stopped
    depends_on:
      qbittorrent:
        condition: service_started
