services:
  qbittorrent:
    image: icyberdeveloper/qbittorrent:5.1.4-r2-ls447
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6882
    volumes:
      - /storage/qbittorrent:/config
      - /mnt/library:/downloads
      - /mnt/tmp:/incomplete
    network_mode: host
    restart: unless-stopped

  false-mirror:
    image: icyberdeveloper/false-mirror:latest
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: false-mirror
    environment:
      - LF_SESSION=9277a695061f92112a9671814ecf230b.2214896
      - TG_BOT_TOKEN=6934685680:AAF1uNpBNVya6ljNFrxahUsli4ZezRstZYo
      - HEALTHCHECK_TG_CHAT_ID=197650166
    volumes:
      - /storage:/storage
      - /mnt/library:/library
      - /mnt/tmp:/incomplete
    network_mode: host
    restart: unless-stopped
    depends_on:
      qbittorrent:
        condition: service_started

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    environment:
      - TELEGRAM_API_ID=37497928
      - TELEGRAM_API_HASH=dd3ad11c85dc97f58c9f523e21aa4e31
      - TELEGRAM_LOCAL=1
    volumes:
      - /storage/telegram-bot-api:/var/lib/telegram-bot-api
      - /mnt/library:/library:ro
    network_mode: host
    restart: unless-stopped

  bot:
    image: icyberdeveloper/nocron:latest
    build:
      context: ..
      dockerfile: deploy/Dockerfile.bot
    container_name: nocron
    environment:
      - TG_BOT_TOKEN=6934685680:AAF1uNpBNVya6ljNFrxahUsli4ZezRstZYo
      - LF_SESSION=9277a695061f92112a9671814ecf230b.2214896
      - HEALTHCHECK_TG_CHAT_ID=197650166
      - TG_BOT_API_URL=http://127.0.0.1:8081
    volumes:
      - /storage:/storage
      - /mnt/library:/library
      - /mnt/tmp:/incomplete
    network_mode: host
    restart: unless-stopped
    depends_on:
      telegram-bot-api:
        condition: service_started
      qbittorrent:
        condition: service_started
