name: ci

on:
  push:
    branches:
      - "main"

env:
  QBITTORRENT_VERSION: "5.1.4-r2-ls447"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push false-mirror
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/Dockerfile
          push: true
          tags: |
            icyberdeveloper/false-mirror:latest
            icyberdeveloper/false-mirror:${{ github.sha }}
      - name: Build and push bot
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/Dockerfile.bot
          push: true
          tags: |
            icyberdeveloper/nocron:latest
            icyberdeveloper/nocron:${{ github.sha }}
      - name: Mirror qBittorrent to Docker Hub
        run: |
          docker pull lscr.io/linuxserver/qbittorrent:${{ env.QBITTORRENT_VERSION }}
          docker tag lscr.io/linuxserver/qbittorrent:${{ env.QBITTORRENT_VERSION }} icyberdeveloper/qbittorrent:${{ env.QBITTORRENT_VERSION }}
          docker tag lscr.io/linuxserver/qbittorrent:${{ env.QBITTORRENT_VERSION }} icyberdeveloper/qbittorrent:latest
          docker push icyberdeveloper/qbittorrent:${{ env.QBITTORRENT_VERSION }}
          docker push icyberdeveloper/qbittorrent:latest
